spring.application.name=jwt-service

spring.config.import=optional:file:local.env[.properties]

eureka.client.server.url.defaultZone=http://localhost:8761/

spring.datasource.diver-class-name=org.postgresql.Driver
spring.datasource.url=${DATASOURCE_URL}
spring.datasource.username=${DATASOURCE_USERNAME}
spring.datasource.password=${DATASOURCE_PASSWORD}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
